name: veltrik
description: "Veltrik Premium Material Library System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  syncfusion_flutter_pdfviewer: ^33.1.47
  syncfusion_flutter_pdf: ^33.1.47
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.12.2
  file_picker: ^11.0.2
  screen_protector: ^1.5.1
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Dependency untuk generate icon otomatis
  flutter_launcher_icons: ^0.13.1

# KONFIGURASI ICON VELTRIK
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0D0F22" # Warna Deep Indigo Veltrik
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/